"""'message'

Revision ID: 8e87df66c7fd
Revises: 2bf5e63b6b86
Create Date: 2023-11-18 19:59:02.349924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e87df66c7fd'
down_revision = '2bf5e63b6b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_posts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tags_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tags_post_id_posts'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_post_id_posts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tags_user_id_users'), type_='foreignkey')
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['id'])

    op.create_table('tags_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('rating', sa.VARCHAR(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_tags_posts_post_id_posts'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_tags_posts_tag_id_tags'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
